import en from "./en";

const vi = {
  ...en,
  common: { ...en.common, cancel: "Hủy", close: "Đóng", done: "Xong", save: "Lưu", create: "Tạo", add: "Thêm", retry: "Thử lại", remove: "Xóa", enterName: "Nhập tên.", restoring: "Đang khôi phục…", actions: "Thao tác", selected: "Đã chọn", loading: "Đang tải…", search: "Tìm kiếm", copy: "Sao chép", reset: "Đặt lại", download: "Tải xuống", name: "Tên", email: "Email", role: "Vai trò", status: "Trạng thái", type: "Loại", modified: "Đã chỉnh sửa", modifiedBy: "Người chỉnh sửa", lastModified: "Chỉnh sửa gần nhất", sortAscending: "sắp xếp tăng dần", sortDescending: "sắp xếp giảm dần", members: "Thành viên" },
  actors: { USER: "Người dùng không xác định", UNKNOWN: "Không rõ", PUBLIC: "Khách qua liên kết", SYSTEM: "Hệ thống", COLLABORATIVE: "Nhiều người chỉnh sửa" },
  dates: { yesterdayAt: "Hôm qua, {{time}}" },
  nav: { ...en.nav, drive: "Drive", recent: "Gần đây", favorites: "Yêu thích", trash: "Thùng rác", admin: "Quản trị", main: "Điều hướng chính", breadcrumb: "Đường dẫn" },
  account: { ...en.account, myAccount: "Tài khoản", profile: "Hồ sơ", language: "Ngôn ngữ", administrator: "Quản trị viên", documentManager: "Quản lý tài liệu", signOut: "Đăng xuất" },
  auth: { ...en.auth, checkingSession: "Đang kiểm tra phiên đăng nhập…", loadingAccount: "Đang tải tài khoản…", signIn: "Đăng nhập", signInDescription: "Đăng nhập để truy cập tài liệu của bạn.", continueWithGoogle: "Tiếp tục với Google", signInWithGoogle: "Đăng nhập bằng Google", signingIn: "Đang đăng nhập…", authenticationFailed: "Xác thực không thành công.", sessionExpired: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.", pendingApproval: "Chờ phê duyệt", accessRequestSubmitted: "Yêu cầu truy cập đã được gửi", googleAccountRegistered: "Tài khoản Google của bạn đã được ghi nhận.", awaitingAdministratorApproval: "Đang chờ quản trị viên phê duyệt", yourAccountWaitingForApproval: "Tài khoản của bạn đang chờ phê duyệt.", trySignInAfterApproval: "Quản trị viên cần phê duyệt tài khoản trước khi bạn có thể truy cập Docs Hub. Sau khi được phê duyệt, bạn có thể đăng nhập lại.", signInAgain: "Đăng nhập lại" },
  admin: { ...en.admin, title: "Quản trị", description: "Quản lý người dùng, nhóm và quyền truy cập Docs Hub.", sections: "Các mục quản trị", users: "Người dùng", usersDescription: "Quản lý những người có thể truy cập Docs Hub.", addUser: "Thêm người dùng", addGoogleAccount: "Thêm tài khoản Google vào Docs Hub.", displayName: "Tên hiển thị", googleEmail: "Email Google", searchUsers: "Tìm người dùng…", groups: "Nhóm", groupsDescription: "Tổ chức người dùng cho quyền tài liệu.", newGroup: "Tạo nhóm", newGroupName: "Tên nhóm mới", searchGroups: "Tìm nhóm…", groupName: "Tên nhóm", manageMembers: "Quản lý thành viên", closeMembers: "Đóng danh sách thành viên", addUserToGroup: "Thêm thành viên…", rename: "Đổi tên", noGroupsYet: "Chưa có nhóm nào.", noGroupsFound: "Không tìm thấy nhóm.", createGroupHint: "Tạo nhóm để tổ chức quyền tài liệu.", tryDifferentSearch: "Thử tìm kiếm khác.", accessDenied: "Bạn không có quyền truy cập khu vực quản trị.", askAdministrator: "Hãy hỏi quản trị viên nếu bạn cần quyền truy cập.", userRequired: "Cần nhập tên hiển thị, email và vai trò.", userAdded: "Đã thêm người dùng. Họ có thể đăng nhập bằng email Google này.", suspendConfirm: "Tạm ngưng {{name}}? Người này sẽ không thể đăng nhập.", setRole: "Đặt vai trò thành {{role}}", suspend: "Tạm ngưng", reactivate: "Kích hoạt lại", approve: "Phê duyệt", accountApproved: "Tài khoản đã được phê duyệt", actionsFor: "Thao tác với {{name}}" },
  profile: { ...en.profile, title: "Hồ sơ", account: "Tài khoản", description: "Thông tin tài khoản đáng tin cậy của bạn.", signInMethod: "Phương thức đăng nhập", connected: "Đã liên kết", notConnected: "Chưa liên kết", googleStatus: "Google ({{status}})" },
  drive: { ...en.drive, title: "Google Drive", description: "Kết nối Drive để khám phá siêu dữ liệu tệp mà không lưu nội dung tệp Drive vào Docs Hub.", notConnected: "Google Drive chưa được kết nối.", connect: "Kết nối Google Drive", connecting: "Đang kết nối…", connected: "Đã kết nối", account: "Tài khoản Google", lastSynced: "Lần đồng bộ gần nhất", neverSynced: "Chưa đồng bộ", lastError: "Trạng thái đồng bộ", syncNow: "Đồng bộ ngay", syncing: "Đang đồng bộ…", syncComplete: "Đã đồng bộ siêu dữ liệu Google Drive.", browse: "Duyệt Drive", disconnect: "Ngắt kết nối", disconnecting: "Đang ngắt kết nối…", disconnectConfirm: "Ngắt Google Drive khỏi Docs Hub?", connectionFailed: "Không thể kết nối Google Drive. Vui lòng thử lại.", browserTitle: "Tệp Google Drive", browserDescription: "Siêu dữ liệu được khám phá từ Google Drive đã kết nối.", connectFromProfile: "Trước tiên hãy kết nối Google Drive trong Hồ sơ.", searchPlaceholder: "Tìm tên tệp Drive", noFiles: "Không tìm thấy tệp Drive đã đồng bộ.", location: "Vị trí", openInGoogle: "Mở trong Google", alreadyInDocsHub: "Đã có trong Docs Hub", addToDocsHub: "Thêm vào Docs Hub", addingToDocsHub: "Đang thêm…", addedToDocsHub: "Đã thêm “{{name}}” vào Docs Hub.", chooseDocsHubFolder: "Chọn thư mục Docs Hub", docsHubRoot: "Gốc Docs Hub", noFolders: "Không có thư mục có thể truy cập tại đây.", addHere: "Thêm tại đây", removeFromDocsHub: "Gỡ khỏi Docs Hub", removeFromDocsHubConfirm: "Gỡ “{{name}}” khỏi Docs Hub? Tệp Google Drive vẫn được giữ nguyên.", removedFromDocsHub: "Đã gỡ “{{name}}” khỏi Docs Hub.", sourceUnavailable: "Nguồn Google Drive này không khả dụng.", sourceStale: "Cần làm mới kết nối Drive", modifiedByUnavailable: "Google Drive không cung cấp", types: { ...en.drive.types, FOLDER: "Thư mục", GOOGLE_DOC: "Google Doc", GOOGLE_SHEET: "Google Sheet", GOOGLE_SLIDE: "Google Slide", PDF: "PDF", IMAGE: "Hình ảnh", VIDEO: "Video", DOCX: "DOCX", XLSX: "XLSX", PPTX: "PPTX", BINARY: "Tệp" }, locations: { ...en.drive.locations, MY_DRIVE: "Drive của tôi", SHARED_WITH_ME: "Được chia sẻ với tôi", SHARED_DRIVE: "Shared Drive", UNKNOWN: "Drive" } },
  files: { ...en.files, title: "Tệp", new: "Tạo mới", newFolder: "Thư mục mới", wordDocument: "Tài liệu Word", spreadsheet: "Bảng tính", presentation: "Bản trình bày", upload: "Tải lên", search: "Tìm tệp", refresh: "Làm mới thư mục", noFiles: "Chưa có tệp nào", noFilesDescription: "Tạo thư mục hoặc tải tệp lên để bắt đầu.", openFolder: "Mở thư mục", open: "Mở", preview: "Xem trước", rename: "Đổi tên", share: "Chia sẻ", favorite: "Thêm vào mục yêu thích", unfavorite: "Xóa khỏi mục yêu thích", versionHistory: "Lịch sử phiên bản", moveToTrash: "Chuyển vào thùng rác", moveToTrashConfirm: "Chuyển “{{name}}” vào thùng rác?", restore: "Khôi phục", deletePermanently: "Xóa vĩnh viễn", created: "Đã tạo “{{name}}”.", uploaded: "Đã tải lên “{{name}}”.", renamed: "Đã cập nhật tên.", movedToTrash: "Đã chuyển “{{name}}” vào thùng rác.", favoriteAdded: "Đã thêm vào mục yêu thích.", favoriteRemoved: "Đã xóa khỏi mục yêu thích.", dateLastOpened: "Mở lần cuối", dateAdded: "Đã thêm", loadingFolder: "Đang tải thư mục…", folderLoadFailed: "Không thể tải thư mục này.", refreshCollection: "Làm mới {{name}}", collectionLoadFailed: "Không thể tải {{name}}.", fileActions: "Thao tác với {{name}}", tableActions: "Thao tác", units: { ...en.files.units, bytes: "B", kilobytes: "KB", megabytes: "MB" } },
  search: { ...en.search, title: "Tìm kiếm", location: "Vị trí", noResults: "Không tìm thấy tệp phù hợp", noResultsDescription: "Thử tìm kiếm khác.", noRecent: "Chưa có tệp gần đây", noFavorites: "Chưa có mục yêu thích", failed: "Không thể tìm kiếm tệp.", results: "Kết quả tìm kiếm", enterQuery: "Nhập tên tệp hoặc thư mục, hoặc từ trong tài liệu đã lập chỉ mục.", queryTooLong: "Cụm từ tìm kiếm quá dài", queryTooLongMessage: "Cụm từ tìm kiếm có thể dài tối đa 200 ký tự.", noFilesForQuery: "Không tìm thấy tệp cho “{{query}}”", loadMore: "Tải thêm", loadingResults: "Đang tải kết quả tìm kiếm", loadingLocation: "Đang tải vị trí…", locationUnavailable: "Không có thông tin vị trí", sharedLocation: "Vị trí được chia sẻ", folder: "Thư mục", file: "Tệp" },
  trash: { ...en.trash, title: "Thùng rác", refresh: "Làm mới thùng rác", empty: "Thùng rác đang trống", trashed: "Đã xóa", autoDelete: "Tự động xóa", restoreFromTrash: "Khôi phục khỏi thùng rác", permanentlyDelete: "Xóa vĩnh viễn", restoreConfirm: "Khôi phục “{{name}}” khỏi thùng rác?", restoreOriginalConfirm: "Khôi phục “{{name}}” về vị trí ban đầu?", deleteConfirm: "Xóa vĩnh viễn “{{name}}”? Hành động này không thể hoàn tác.", restored: "Đã khôi phục “{{name}}”.", deleted: "Đã xóa vĩnh viễn “{{name}}”.", actionsFor: "Thao tác với {{name}}" },
  share: { ...en.share, title: "Chia sẻ “{{name}}”", close: "Đóng chia sẻ", loading: "Đang tải cài đặt chia sẻ…", peopleWithAccess: "Những người có quyền truy cập", noDirectPermissions: "Không có quyền trực tiếp.", addPeopleOrGroups: "Thêm người hoặc nhóm", addPersonOrGroup: "Thêm người hoặc nhóm", people: "Người dùng", groups: "Nhóm", searchPeople: "Tìm người dùng", searchGroups: "Tìm nhóm", searchType: "Loại tìm kiếm", typeToSearch: "Nhập ít nhất 2 ký tự để tìm kiếm.", noMatchingPeople: "Không tìm thấy người dùng phù hợp.", noMatchingGroups: "Không tìm thấy nhóm phù hợp.", searchResults: "Kết quả tìm kiếm", sharingWith: "Đang chia sẻ với", roleFor: "Vai trò của {{name}}", generalAccess: "Quyền truy cập chung", anyoneWithLink: "Bất kỳ ai có liên kết", anyoneWithLinkViewer: "Bất kỳ ai có liên kết — Người xem", anyoneWithLinkEditor: "Bất kỳ ai có liên kết — Người chỉnh sửa", restricted: "Bị giới hạn", anyoneCanView: "Bất kỳ ai có liên kết đều có thể xem.", anyoneCanEdit: "Bất kỳ ai có liên kết đều có thể chỉnh sửa tài liệu này.", onlyPeopleCanView: "Chỉ những người có quyền mới có thể xem.", anyoneCanViewAria: "Bất kỳ ai có liên kết đều có thể xem", documentLink: "Liên kết tài liệu", copyLink: "Sao chép liên kết", advancedAccess: "Quyền truy cập nâng cao", inheritPermissions: "Kế thừa quyền từ thư mục cha", permissionAdded: "Đã thêm quyền.", permissionUpdated: "Đã cập nhật quyền.", permissionRemoved: "Đã xóa quyền.", inheritanceUpdated: "Đã cập nhật kế thừa quyền.", stopInheritanceConfirm: "Dừng kế thừa quyền truy cập từ thư mục cha?", directUserPermission: "Quyền trực tiếp của người dùng", directGroupPermission: "Quyền trực tiếp của nhóm", linkCopied: "Đã sao chép liên kết.", linkCopyFailed: "Không thể sao chép liên kết.", generalAccessUpdated: "Đã cập nhật quyền truy cập chung.", permission: "Quyền", removeAccess: "Xóa quyền truy cập" },
  versions: { ...en.versions, title: "Lịch sử phiên bản", current: "Hiện tại", version: "Phiên bản {{number}}", restoreThisVersion: "Khôi phục phiên bản này", restoreConfirm: "Tạo phiên bản mới từ Phiên bản {{number}}? Các phiên bản hiện có sẽ không thay đổi.", restored: "Đã khôi phục phiên bản.", downloadVersion: "Tải xuống phiên bản", loading: "Đang tải các phiên bản…", createdBy: "Người tạo", sources: { UPLOAD: "Đã tải lên", EDITOR: "Đã chỉnh sửa", RESTORE: "Đã khôi phục", SYSTEM: "Hệ thống" } },
  editor: { ...en.editor, opening: "Đang mở trình chỉnh sửa…", saving: "Đang lưu thay đổi…", savingChanges: "Đang lưu thay đổi...", changesSaved: "Đã lưu thay đổi.", saveFailed: "Không thể lưu thay đổi.", stillSaving: "Tệp đang được lưu. Vui lòng thử lại sau giây lát.", failed: "Không thể mở trình chỉnh sửa tài liệu.", unavailable: "Trình chỉnh sửa tài liệu hiện không khả dụng.", title: "Trình chỉnh sửa tài liệu", ariaTitle: "Trình chỉnh sửa tài liệu: {{title}}", resize: "Thay đổi kích thước trình chỉnh sửa" },
  document: { ...en.document, accessDeniedTitle: "Bạn không có quyền truy cập tài liệu này.", accessDeniedMessage: "Nếu bạn cho rằng mình cần quyền truy cập, hãy liên hệ chủ sở hữu hoặc quản trị viên.", linkUnavailable: "Liên kết này không còn khả dụng.", linkUnavailableMessage: "Hãy kiểm tra liên kết hoặc yêu cầu người chia sẻ gửi liên kết mới.", signIn: "Đăng nhập", latestChangesSaving: "Các thay đổi mới nhất vẫn đang được lưu.", tryAgainSoon: "Vui lòng thử lại sau giây lát." },
  preview: { ...en.preview, unavailableTitle: "Không thể xem trước", unavailableMessage: "Không thể xem trước loại tệp này tại đây.", failedTitle: "Xem trước không khả dụng", failedMessage: "Không thể tải tệp để xem trước.", loading: "Đang tải bản xem trước…", close: "Đóng bản xem trước" },
  errors: { ...en.errors, generic: "Đã xảy ra lỗi. Vui lòng thử lại.", directoryUnavailable: "Không thể tìm kiếm danh bạ." },
  roles: { ADMIN: "Quản trị viên", DOCUMENT_MANAGER: "Quản lý tài liệu", VIEWER: "Người xem", EDITOR: "Người chỉnh sửa", OWNER: "Chủ sở hữu" },
  statuses: { INVITED: "Đã mời", PENDING_APPROVAL: "Chờ phê duyệt", ACTIVE: "Đang hoạt động", SUSPENDED: "Đã tạm ngưng" },
  principalTypes: { USER: "Người dùng", GROUP: "Nhóm" },
  language: { language: "Ngôn ngữ", vietnamese: "Tiếng Việt", english: "English" },
} as const;

export default vi;
